/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Notice {
  'title' : string,
  'content' : string,
  'date' : string,
}
export interface _SERVICE {
  'addCertificate' : ActorMethod<
    [string, string, string, string, boolean],
    undefined
  >,
  'addNotice' : ActorMethod<[string, string, string], undefined>,
  'addResult' : ActorMethod<[string, bigint, string], undefined>,
  'addStudentCredential' : ActorMethod<[string, string], undefined>,
  'checkResult' : ActorMethod<[string], [bigint, string]>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'studentLogin' : ActorMethod<[string, string], boolean>,
  'submitApplication' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'submitContactMessage' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'verifyCertificate' : ActorMethod<[string], [boolean, string]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];