/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Notice = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'date' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCertificate' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'addResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'addStudentCredential' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkResult' : IDL.Func([IDL.Text], [IDL.Nat, IDL.Text], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'submitApplication' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'submitContactMessage' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool, IDL.Text], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Notice = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'date' : IDL.Text,
  });
  
  return IDL.Service({
    'addCertificate' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'addResult' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'addStudentCredential' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkResult' : IDL.Func([IDL.Text], [IDL.Nat, IDL.Text], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'studentLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
    'submitApplication' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'submitContactMessage' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'verifyCertificate' : IDL.Func([IDL.Text], [IDL.Bool, IDL.Text], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };